// Content below is autogenerated by ojster template engine
// usually there is no reason to edit it manually
goog.provide('gcinui.templates.Form');

goog.require('ojster');
goog.require('goog.array');

/**
 * @param {Object=} opt_data
 * @param {Object=} opt_ctx
 * @param {Object=} opt_writer
 * @constructor
 * @extends {ojster.Template}
 */
gcinui.templates.Form = function(opt_data, opt_ctx, opt_writer) {
	goog.base(this, opt_data, opt_ctx, opt_writer);
};
goog.inherits(gcinui.templates.Form, ojster.Template);

gcinui.templates.Form.prototype.renderBlockMain = function() { // @7:1
	var self = this;
	var d = this.data, vars = this.vars;
	self.writer.write(
		'<form class="',
		self.baseCssName, // @8:14
		'"><div class="',
		goog.getCssName(/** @type {string} */ (self.baseCssName), 'buttons'), // @9:15
		'"><span class="',
		goog.getCssName(/** @type {string} */ (self.baseCssName), 'copy'), // @9:49
		'"></span> <span class="',
		goog.getCssName(/** @type {string} */ (self.baseCssName), 'prettify'), // @9:88
		' ',
		goog.getCssName(/** @type {string} */ (self.baseCssName), 'hidden'), // @9:109
		'"></span></div><div class="',
		goog.getCssName(/** @type {string} */ (self.baseCssName), 'fields'), // @10:15
		'"></div><div class="',
		goog.getCssName(/** @type {string} */ (self.baseCssName), 'result'), // @11:15
		' ',
		goog.getCssName(/** @type {string} */ (self.baseCssName), 'hidden'), // @11:34
		'"></div></form>'
	);
}; // @13:1
